version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amazon
      MYSQL_USER: amazon
      MYSQL_PASSWORD: amazon
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/table.sql:/docker-entrypoint-initdb.d/table.sql
    networks:
      - amazon-network

volumes:
  mysql_data:

networks:
  amazon-network:
    driver: bridge