// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: amazon_ups-1.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpsService_RequestPickup_FullMethodName   = "/duke.ece568.amazon_ups.UpsService/RequestPickup"
	UpsService_RequestRedirect_FullMethodName = "/duke.ece568.amazon_ups.UpsService/RequestRedirect"
	UpsService_RequestCancel_FullMethodName   = "/duke.ece568.amazon_ups.UpsService/RequestCancel"
	UpsService_NotifyLoadReady_FullMethodName = "/duke.ece568.amazon_ups.UpsService/NotifyLoadReady"
)

// UpsServiceClient is the client API for UpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UPS Service called by Amazon
type UpsServiceClient interface {
	// Request UPS to pick up a package from Amazon's warehouse
	RequestPickup(ctx context.Context, in *PickupRequest, opts ...grpc.CallOption) (*PickupResp, error)
	// Request redirect of a package to a new destination
	RequestRedirect(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*RedirectResp, error)
	// Request cancellation of a package pickup/delivery
	RequestCancel(ctx context.Context, in *CancelOrder, opts ...grpc.CallOption) (*CancelResp, error)
	// Notify UPS that the package is ready for loading
	NotifyLoadReady(ctx context.Context, in *LoadReady, opts ...grpc.CallOption) (*Ack, error)
}

type upsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpsServiceClient(cc grpc.ClientConnInterface) UpsServiceClient {
	return &upsServiceClient{cc}
}

func (c *upsServiceClient) RequestPickup(ctx context.Context, in *PickupRequest, opts ...grpc.CallOption) (*PickupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickupResp)
	err := c.cc.Invoke(ctx, UpsService_RequestPickup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upsServiceClient) RequestRedirect(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*RedirectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectResp)
	err := c.cc.Invoke(ctx, UpsService_RequestRedirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upsServiceClient) RequestCancel(ctx context.Context, in *CancelOrder, opts ...grpc.CallOption) (*CancelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResp)
	err := c.cc.Invoke(ctx, UpsService_RequestCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upsServiceClient) NotifyLoadReady(ctx context.Context, in *LoadReady, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, UpsService_NotifyLoadReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsServiceServer is the server API for UpsService service.
// All implementations must embed UnimplementedUpsServiceServer
// for forward compatibility.
//
// UPS Service called by Amazon
type UpsServiceServer interface {
	// Request UPS to pick up a package from Amazon's warehouse
	RequestPickup(context.Context, *PickupRequest) (*PickupResp, error)
	// Request redirect of a package to a new destination
	RequestRedirect(context.Context, *Redirect) (*RedirectResp, error)
	// Request cancellation of a package pickup/delivery
	RequestCancel(context.Context, *CancelOrder) (*CancelResp, error)
	// Notify UPS that the package is ready for loading
	NotifyLoadReady(context.Context, *LoadReady) (*Ack, error)
	mustEmbedUnimplementedUpsServiceServer()
}

// UnimplementedUpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpsServiceServer struct{}

func (UnimplementedUpsServiceServer) RequestPickup(context.Context, *PickupRequest) (*PickupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPickup not implemented")
}
func (UnimplementedUpsServiceServer) RequestRedirect(context.Context, *Redirect) (*RedirectResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRedirect not implemented")
}
func (UnimplementedUpsServiceServer) RequestCancel(context.Context, *CancelOrder) (*CancelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCancel not implemented")
}
func (UnimplementedUpsServiceServer) NotifyLoadReady(context.Context, *LoadReady) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyLoadReady not implemented")
}
func (UnimplementedUpsServiceServer) mustEmbedUnimplementedUpsServiceServer() {}
func (UnimplementedUpsServiceServer) testEmbeddedByValue()                    {}

// UnsafeUpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpsServiceServer will
// result in compilation errors.
type UnsafeUpsServiceServer interface {
	mustEmbedUnimplementedUpsServiceServer()
}

func RegisterUpsServiceServer(s grpc.ServiceRegistrar, srv UpsServiceServer) {
	// If the following call panics, it indicates UnimplementedUpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpsService_ServiceDesc, srv)
}

func _UpsService_RequestPickup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsServiceServer).RequestPickup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsService_RequestPickup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsServiceServer).RequestPickup(ctx, req.(*PickupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpsService_RequestRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Redirect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsServiceServer).RequestRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsService_RequestRedirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsServiceServer).RequestRedirect(ctx, req.(*Redirect))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpsService_RequestCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsServiceServer).RequestCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsService_RequestCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsServiceServer).RequestCancel(ctx, req.(*CancelOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpsService_NotifyLoadReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadReady)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsServiceServer).NotifyLoadReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpsService_NotifyLoadReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsServiceServer).NotifyLoadReady(ctx, req.(*LoadReady))
	}
	return interceptor(ctx, in, info, handler)
}

// UpsService_ServiceDesc is the grpc.ServiceDesc for UpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duke.ece568.amazon_ups.UpsService",
	HandlerType: (*UpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPickup",
			Handler:    _UpsService_RequestPickup_Handler,
		},
		{
			MethodName: "RequestRedirect",
			Handler:    _UpsService_RequestRedirect_Handler,
		},
		{
			MethodName: "RequestCancel",
			Handler:    _UpsService_RequestCancel_Handler,
		},
		{
			MethodName: "NotifyLoadReady",
			Handler:    _UpsService_NotifyLoadReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amazon_ups-1.proto",
}

const (
	AmazonService_NotifyTruckArrived_FullMethodName     = "/duke.ece568.amazon_ups.AmazonService/NotifyTruckArrived"
	AmazonService_NotifyDeliveryStarted_FullMethodName  = "/duke.ece568.amazon_ups.AmazonService/NotifyDeliveryStarted"
	AmazonService_NotifyDeliveryComplete_FullMethodName = "/duke.ece568.amazon_ups.AmazonService/NotifyDeliveryComplete"
	AmazonService_NotifyRedirectRequest_FullMethodName  = "/duke.ece568.amazon_ups.AmazonService/NotifyRedirectRequest"
)

// AmazonServiceClient is the client API for AmazonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Amazon Service called by UPS
type AmazonServiceClient interface {
	// Notify Amazon that the truck has arrived at the warehouse
	NotifyTruckArrived(ctx context.Context, in *TruckArrived, opts ...grpc.CallOption) (*Ack, error)
	// Notify Amazon that the delivery has started
	NotifyDeliveryStarted(ctx context.Context, in *DeliveryStarted, opts ...grpc.CallOption) (*Ack, error)
	// Notify Amazon that the delivery is complete
	NotifyDeliveryComplete(ctx context.Context, in *DeliveryComplete, opts ...grpc.CallOption) (*Ack, error)
	// Notify Amazon of a redirect request from UPS
	NotifyRedirectRequest(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Ack, error)
}

type amazonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmazonServiceClient(cc grpc.ClientConnInterface) AmazonServiceClient {
	return &amazonServiceClient{cc}
}

func (c *amazonServiceClient) NotifyTruckArrived(ctx context.Context, in *TruckArrived, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AmazonService_NotifyTruckArrived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amazonServiceClient) NotifyDeliveryStarted(ctx context.Context, in *DeliveryStarted, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AmazonService_NotifyDeliveryStarted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amazonServiceClient) NotifyDeliveryComplete(ctx context.Context, in *DeliveryComplete, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AmazonService_NotifyDeliveryComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amazonServiceClient) NotifyRedirectRequest(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AmazonService_NotifyRedirectRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmazonServiceServer is the server API for AmazonService service.
// All implementations must embed UnimplementedAmazonServiceServer
// for forward compatibility.
//
// Amazon Service called by UPS
type AmazonServiceServer interface {
	// Notify Amazon that the truck has arrived at the warehouse
	NotifyTruckArrived(context.Context, *TruckArrived) (*Ack, error)
	// Notify Amazon that the delivery has started
	NotifyDeliveryStarted(context.Context, *DeliveryStarted) (*Ack, error)
	// Notify Amazon that the delivery is complete
	NotifyDeliveryComplete(context.Context, *DeliveryComplete) (*Ack, error)
	// Notify Amazon of a redirect request from UPS
	NotifyRedirectRequest(context.Context, *Redirect) (*Ack, error)
	mustEmbedUnimplementedAmazonServiceServer()
}

// UnimplementedAmazonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmazonServiceServer struct{}

func (UnimplementedAmazonServiceServer) NotifyTruckArrived(context.Context, *TruckArrived) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyTruckArrived not implemented")
}
func (UnimplementedAmazonServiceServer) NotifyDeliveryStarted(context.Context, *DeliveryStarted) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyDeliveryStarted not implemented")
}
func (UnimplementedAmazonServiceServer) NotifyDeliveryComplete(context.Context, *DeliveryComplete) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyDeliveryComplete not implemented")
}
func (UnimplementedAmazonServiceServer) NotifyRedirectRequest(context.Context, *Redirect) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyRedirectRequest not implemented")
}
func (UnimplementedAmazonServiceServer) mustEmbedUnimplementedAmazonServiceServer() {}
func (UnimplementedAmazonServiceServer) testEmbeddedByValue()                       {}

// UnsafeAmazonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmazonServiceServer will
// result in compilation errors.
type UnsafeAmazonServiceServer interface {
	mustEmbedUnimplementedAmazonServiceServer()
}

func RegisterAmazonServiceServer(s grpc.ServiceRegistrar, srv AmazonServiceServer) {
	// If the following call panics, it indicates UnimplementedAmazonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmazonService_ServiceDesc, srv)
}

func _AmazonService_NotifyTruckArrived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruckArrived)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazonServiceServer).NotifyTruckArrived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmazonService_NotifyTruckArrived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazonServiceServer).NotifyTruckArrived(ctx, req.(*TruckArrived))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmazonService_NotifyDeliveryStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryStarted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazonServiceServer).NotifyDeliveryStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmazonService_NotifyDeliveryStarted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazonServiceServer).NotifyDeliveryStarted(ctx, req.(*DeliveryStarted))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmazonService_NotifyDeliveryComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryComplete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazonServiceServer).NotifyDeliveryComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmazonService_NotifyDeliveryComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazonServiceServer).NotifyDeliveryComplete(ctx, req.(*DeliveryComplete))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmazonService_NotifyRedirectRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Redirect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazonServiceServer).NotifyRedirectRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmazonService_NotifyRedirectRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazonServiceServer).NotifyRedirectRequest(ctx, req.(*Redirect))
	}
	return interceptor(ctx, in, info, handler)
}

// AmazonService_ServiceDesc is the grpc.ServiceDesc for AmazonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmazonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duke.ece568.amazon_ups.AmazonService",
	HandlerType: (*AmazonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyTruckArrived",
			Handler:    _AmazonService_NotifyTruckArrived_Handler,
		},
		{
			MethodName: "NotifyDeliveryStarted",
			Handler:    _AmazonService_NotifyDeliveryStarted_Handler,
		},
		{
			MethodName: "NotifyDeliveryComplete",
			Handler:    _AmazonService_NotifyDeliveryComplete_Handler,
		},
		{
			MethodName: "NotifyRedirectRequest",
			Handler:    _AmazonService_NotifyRedirectRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amazon_ups-1.proto",
}
