// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: amazon_ups-1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_amazon_ups_1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_amazon_ups_1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{1}
}

func (x *ItemInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_amazon_ups_1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Amazon to UPS messages
type PickupRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Seqnum          int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	UpsUserId       string                 `protobuf:"bytes,2,opt,name=ups_user_id,json=upsUserId,proto3" json:"ups_user_id,omitempty"`
	Items           []*ItemInfo            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	OrderId         int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WarehouseId     int32                  `protobuf:"varint,5,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	UserDestination *Coordinate            `protobuf:"bytes,6,opt,name=user_destination,json=userDestination,proto3" json:"user_destination,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PickupRequest) Reset() {
	*x = PickupRequest{}
	mi := &file_amazon_ups_1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupRequest) ProtoMessage() {}

func (x *PickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupRequest.ProtoReflect.Descriptor instead.
func (*PickupRequest) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{3}
}

func (x *PickupRequest) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *PickupRequest) GetUpsUserId() string {
	if x != nil {
		return x.UpsUserId
	}
	return ""
}

func (x *PickupRequest) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PickupRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PickupRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *PickupRequest) GetUserDestination() *Coordinate {
	if x != nil {
		return x.UserDestination
	}
	return nil
}

type Redirect struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seqnum         int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId      int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	NewDestination *Coordinate            `protobuf:"bytes,3,opt,name=new_destination,json=newDestination,proto3" json:"new_destination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Redirect) Reset() {
	*x = Redirect{}
	mi := &file_amazon_ups_1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redirect) ProtoMessage() {}

func (x *Redirect) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redirect.ProtoReflect.Descriptor instead.
func (*Redirect) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{4}
}

func (x *Redirect) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *Redirect) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *Redirect) GetNewDestination() *Coordinate {
	if x != nil {
		return x.NewDestination
	}
	return nil
}

type CancelOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrder) Reset() {
	*x = CancelOrder{}
	mi := &file_amazon_ups_1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrder) ProtoMessage() {}

func (x *CancelOrder) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrder.ProtoReflect.Descriptor instead.
func (*CancelOrder) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrder) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *CancelOrder) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

type LoadReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadReady) Reset() {
	*x = LoadReady{}
	mi := &file_amazon_ups_1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReady) ProtoMessage() {}

func (x *LoadReady) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReady.ProtoReflect.Descriptor instead.
func (*LoadReady) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{6}
}

func (x *LoadReady) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *LoadReady) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

// UPS to Amazon messages
type PickupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TruckId       int32                  `protobuf:"varint,4,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupResp) Reset() {
	*x = PickupResp{}
	mi := &file_amazon_ups_1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupResp) ProtoMessage() {}

func (x *PickupResp) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupResp.ProtoReflect.Descriptor instead.
func (*PickupResp) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{7}
}

func (x *PickupResp) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *PickupResp) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *PickupResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PickupResp) GetTruckId() int32 {
	if x != nil {
		return x.TruckId
	}
	return 0
}

type RedirectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResp) Reset() {
	*x = RedirectResp{}
	mi := &file_amazon_ups_1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResp) ProtoMessage() {}

func (x *RedirectResp) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResp.ProtoReflect.Descriptor instead.
func (*RedirectResp) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectResp) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *RedirectResp) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *RedirectResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RedirectResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResp) Reset() {
	*x = CancelResp{}
	mi := &file_amazon_ups_1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResp) ProtoMessage() {}

func (x *CancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResp.ProtoReflect.Descriptor instead.
func (*CancelResp) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{9}
}

func (x *CancelResp) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *CancelResp) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *CancelResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TruckArrived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	TruckId       int32                  `protobuf:"varint,3,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	WarehouseId   int32                  `protobuf:"varint,4,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruckArrived) Reset() {
	*x = TruckArrived{}
	mi := &file_amazon_ups_1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruckArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckArrived) ProtoMessage() {}

func (x *TruckArrived) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckArrived.ProtoReflect.Descriptor instead.
func (*TruckArrived) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{10}
}

func (x *TruckArrived) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *TruckArrived) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *TruckArrived) GetTruckId() int32 {
	if x != nil {
		return x.TruckId
	}
	return 0
}

func (x *TruckArrived) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type DeliveryStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStarted) Reset() {
	*x = DeliveryStarted{}
	mi := &file_amazon_ups_1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStarted) ProtoMessage() {}

func (x *DeliveryStarted) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStarted.ProtoReflect.Descriptor instead.
func (*DeliveryStarted) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{11}
}

func (x *DeliveryStarted) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *DeliveryStarted) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

type DeliveryComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        int64                  `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	PackageId     int64                  `protobuf:"varint,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryComplete) Reset() {
	*x = DeliveryComplete{}
	mi := &file_amazon_ups_1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryComplete) ProtoMessage() {}

func (x *DeliveryComplete) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_ups_1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryComplete.ProtoReflect.Descriptor instead.
func (*DeliveryComplete) Descriptor() ([]byte, []int) {
	return file_amazon_ups_1_proto_rawDescGZIP(), []int{12}
}

func (x *DeliveryComplete) GetSeqnum() int64 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

func (x *DeliveryComplete) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

var File_amazon_ups_1_proto protoreflect.FileDescriptor

const file_amazon_ups_1_proto_rawDesc = "" +
	"\n" +
	"\x12amazon_ups-1.proto\x12\x16duke.ece568.amazon_ups\"(\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"C\n" +
	"\bItemInfo\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"Q\n" +
	"\x03Ack\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8c\x02\n" +
	"\rPickupRequest\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1e\n" +
	"\vups_user_id\x18\x02 \x01(\tR\tupsUserId\x126\n" +
	"\x05items\x18\x03 \x03(\v2 .duke.ece568.amazon_ups.ItemInfoR\x05items\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\x12!\n" +
	"\fwarehouse_id\x18\x05 \x01(\x05R\vwarehouseId\x12M\n" +
	"\x10user_destination\x18\x06 \x01(\v2\".duke.ece568.amazon_ups.CoordinateR\x0fuserDestination\"\x8e\x01\n" +
	"\bRedirect\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\x12K\n" +
	"\x0fnew_destination\x18\x03 \x01(\v2\".duke.ece568.amazon_ups.CoordinateR\x0enewDestination\"D\n" +
	"\vCancelOrder\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\"B\n" +
	"\tLoadReady\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\"y\n" +
	"\n" +
	"PickupResp\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x19\n" +
	"\btruck_id\x18\x04 \x01(\x05R\atruckId\"w\n" +
	"\fRedirectResp\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"u\n" +
	"\n" +
	"CancelResp\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x83\x01\n" +
	"\fTruckArrived\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\x12\x19\n" +
	"\btruck_id\x18\x03 \x01(\x05R\atruckId\x12!\n" +
	"\fwarehouse_id\x18\x04 \x01(\x05R\vwarehouseId\"H\n" +
	"\x0fDeliveryStarted\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId\"I\n" +
	"\x10DeliveryComplete\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\x03R\x06seqnum\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\x03R\tpackageId2\xf0\x02\n" +
	"\n" +
	"UpsService\x12Z\n" +
	"\rRequestPickup\x12%.duke.ece568.amazon_ups.PickupRequest\x1a\".duke.ece568.amazon_ups.PickupResp\x12Y\n" +
	"\x0fRequestRedirect\x12 .duke.ece568.amazon_ups.Redirect\x1a$.duke.ece568.amazon_ups.RedirectResp\x12X\n" +
	"\rRequestCancel\x12#.duke.ece568.amazon_ups.CancelOrder\x1a\".duke.ece568.amazon_ups.CancelResp\x12Q\n" +
	"\x0fNotifyLoadReady\x12!.duke.ece568.amazon_ups.LoadReady\x1a\x1b.duke.ece568.amazon_ups.Ack2\x80\x03\n" +
	"\rAmazonService\x12W\n" +
	"\x12NotifyTruckArrived\x12$.duke.ece568.amazon_ups.TruckArrived\x1a\x1b.duke.ece568.amazon_ups.Ack\x12]\n" +
	"\x15NotifyDeliveryStarted\x12'.duke.ece568.amazon_ups.DeliveryStarted\x1a\x1b.duke.ece568.amazon_ups.Ack\x12_\n" +
	"\x16NotifyDeliveryComplete\x12(.duke.ece568.amazon_ups.DeliveryComplete\x1a\x1b.duke.ece568.amazon_ups.Ack\x12V\n" +
	"\x15NotifyRedirectRequest\x12 .duke.ece568.amazon_ups.Redirect\x1a\x1b.duke.ece568.amazon_ups.AckB\x17Z\x15mini-amazon-ups/protob\x06proto3"

var (
	file_amazon_ups_1_proto_rawDescOnce sync.Once
	file_amazon_ups_1_proto_rawDescData []byte
)

func file_amazon_ups_1_proto_rawDescGZIP() []byte {
	file_amazon_ups_1_proto_rawDescOnce.Do(func() {
		file_amazon_ups_1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amazon_ups_1_proto_rawDesc), len(file_amazon_ups_1_proto_rawDesc)))
	})
	return file_amazon_ups_1_proto_rawDescData
}

var file_amazon_ups_1_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_amazon_ups_1_proto_goTypes = []any{
	(*Coordinate)(nil),       // 0: duke.ece568.amazon_ups.Coordinate
	(*ItemInfo)(nil),         // 1: duke.ece568.amazon_ups.ItemInfo
	(*Ack)(nil),              // 2: duke.ece568.amazon_ups.Ack
	(*PickupRequest)(nil),    // 3: duke.ece568.amazon_ups.PickupRequest
	(*Redirect)(nil),         // 4: duke.ece568.amazon_ups.Redirect
	(*CancelOrder)(nil),      // 5: duke.ece568.amazon_ups.CancelOrder
	(*LoadReady)(nil),        // 6: duke.ece568.amazon_ups.LoadReady
	(*PickupResp)(nil),       // 7: duke.ece568.amazon_ups.PickupResp
	(*RedirectResp)(nil),     // 8: duke.ece568.amazon_ups.RedirectResp
	(*CancelResp)(nil),       // 9: duke.ece568.amazon_ups.CancelResp
	(*TruckArrived)(nil),     // 10: duke.ece568.amazon_ups.TruckArrived
	(*DeliveryStarted)(nil),  // 11: duke.ece568.amazon_ups.DeliveryStarted
	(*DeliveryComplete)(nil), // 12: duke.ece568.amazon_ups.DeliveryComplete
}
var file_amazon_ups_1_proto_depIdxs = []int32{
	1,  // 0: duke.ece568.amazon_ups.PickupRequest.items:type_name -> duke.ece568.amazon_ups.ItemInfo
	0,  // 1: duke.ece568.amazon_ups.PickupRequest.user_destination:type_name -> duke.ece568.amazon_ups.Coordinate
	0,  // 2: duke.ece568.amazon_ups.Redirect.new_destination:type_name -> duke.ece568.amazon_ups.Coordinate
	3,  // 3: duke.ece568.amazon_ups.UpsService.RequestPickup:input_type -> duke.ece568.amazon_ups.PickupRequest
	4,  // 4: duke.ece568.amazon_ups.UpsService.RequestRedirect:input_type -> duke.ece568.amazon_ups.Redirect
	5,  // 5: duke.ece568.amazon_ups.UpsService.RequestCancel:input_type -> duke.ece568.amazon_ups.CancelOrder
	6,  // 6: duke.ece568.amazon_ups.UpsService.NotifyLoadReady:input_type -> duke.ece568.amazon_ups.LoadReady
	10, // 7: duke.ece568.amazon_ups.AmazonService.NotifyTruckArrived:input_type -> duke.ece568.amazon_ups.TruckArrived
	11, // 8: duke.ece568.amazon_ups.AmazonService.NotifyDeliveryStarted:input_type -> duke.ece568.amazon_ups.DeliveryStarted
	12, // 9: duke.ece568.amazon_ups.AmazonService.NotifyDeliveryComplete:input_type -> duke.ece568.amazon_ups.DeliveryComplete
	4,  // 10: duke.ece568.amazon_ups.AmazonService.NotifyRedirectRequest:input_type -> duke.ece568.amazon_ups.Redirect
	7,  // 11: duke.ece568.amazon_ups.UpsService.RequestPickup:output_type -> duke.ece568.amazon_ups.PickupResp
	8,  // 12: duke.ece568.amazon_ups.UpsService.RequestRedirect:output_type -> duke.ece568.amazon_ups.RedirectResp
	9,  // 13: duke.ece568.amazon_ups.UpsService.RequestCancel:output_type -> duke.ece568.amazon_ups.CancelResp
	2,  // 14: duke.ece568.amazon_ups.UpsService.NotifyLoadReady:output_type -> duke.ece568.amazon_ups.Ack
	2,  // 15: duke.ece568.amazon_ups.AmazonService.NotifyTruckArrived:output_type -> duke.ece568.amazon_ups.Ack
	2,  // 16: duke.ece568.amazon_ups.AmazonService.NotifyDeliveryStarted:output_type -> duke.ece568.amazon_ups.Ack
	2,  // 17: duke.ece568.amazon_ups.AmazonService.NotifyDeliveryComplete:output_type -> duke.ece568.amazon_ups.Ack
	2,  // 18: duke.ece568.amazon_ups.AmazonService.NotifyRedirectRequest:output_type -> duke.ece568.amazon_ups.Ack
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_amazon_ups_1_proto_init() }
func file_amazon_ups_1_proto_init() {
	if File_amazon_ups_1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amazon_ups_1_proto_rawDesc), len(file_amazon_ups_1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_amazon_ups_1_proto_goTypes,
		DependencyIndexes: file_amazon_ups_1_proto_depIdxs,
		MessageInfos:      file_amazon_ups_1_proto_msgTypes,
	}.Build()
	File_amazon_ups_1_proto = out.File
	file_amazon_ups_1_proto_goTypes = nil
	file_amazon_ups_1_proto_depIdxs = nil
}
